### ISSUE TITLE
Add problem description

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-ECTA#5] opened 2015-06-17 07:58 UTC
And I need it now
- @fergunet or @raiben add MADE description, a couple of paragraphs. 
- @deantares or @amorag or @fergunet add planet wars description.
- @amorag or @fliberatore or @pacastillo add Ms. Pacman description.

Please don't copy-paste from other papers. Just a couple of paragraphs, short description saying mainly what the problem is, how fitness is evaluated and how selection had been made so far without taking into account noise (or taking it)

**Comment by pacastillo** [comment] 2015-06-17 10:48
A ver qué te parece lo siguiente para el Ms. Pac-Man:

---

Pac-Man game, released in 1981, has resulted in several variants. One of the most famous Ms. Pac-Man, that extends the mechanics of the original game with several features. 
The most interesting is the possibility of applying different strategies to the ghosts’ behavior. Another one is the inclusion of a random movement to prevent the use of patterns to clear each round.

Recently, researchers are paying more attention to this game due to the Ms. Pac-Man vs Ghosts competition, where participants can submit controllers for both Ms. Pac-Man and the Ghost Team. 
In this competition, the objective of Ms. Pac-Man is to maximize the final score, while the objective of the Ghost Team is to minimize it. 

Proposed implementation follows the following restrictions for the Ghost Team:
- A ghost can never stop and if it is in a corridor it must move forward.
- A ghost can choose its direction only at a junction.
- Every time a ghost is at a junction the controller has to provide a direction from the set of feasible directions.
- After 4000 game ticks, a level is considered completed and the game moves on to the next level.

---

**Comment by amorag** [comment] 2015-06-17 10:49
Sigo sin saber por qué hablamos en inglés siendo todos españoles.

Voy a hacer lo del Genebot, pero ¿qué datos tienes?

Dependiendo de cuáles sean el fitness será uno u otro… ¿Antares sabes qué datos son?

De: Juan Julián Merelo Guervós [mailto:notifications@github.com] 
Enviado el: miércoles, 17 de junio de 2015 9:58
Para: geneura-papers/2015-ECTA
CC: Antonio Mora
Asunto: [2015-ECTA] Add problem description (#5)

And I need it now
-   @fergunet https://github.com/fergunet  or @raiben https://github.com/raiben  add MADE description, a couple of paragraphs. 
-   @deantares https://github.com/deantares  or @amorag https://github.com/amorag  or @fergunet https://github.com/fergunet  add planet wars description.
-   @amorag https://github.com/amorag  or @fliberatore https://github.com/fliberatore  or @pacastillo https://github.com/pacastillo  add Ms. Pacman description.

Please don't copy-paste from other papers. Just a couple of paragraphs, short description saying mainly what the problem is, how fitness is evaluated and how selection had been made so far without taking into account noise (or taking it)

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2015-ECTA/issues/5 .  https://github.com/notifications/beacon/AC6-WuNpxsLY6nuM5G1iD3iNuX3c1EgVks5oUSATgaJpZM4FFHwd.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5961 / Base de datos de virus: 4365/10030 - Fecha de publicación: 06/16/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5961 / Base de datos de virus: 4355/9987 - Fecha de publicación: 06/10/15

**Comment by unintendedbear** [comment] 2015-06-17 11:00
> Sigo sin saber por qué hablamos en inglés siendo todos españoles.

Easy. That significantly increases the possibility of others being interested in our work :) Or that maybe some others want to contribute.
If it's open it should be English written.
In addition, paper it's English written.
Aaaaand what's more addition is free practise for all.

**Comment by fergunet** [comment] 2015-06-17 11:01
I've added information about MADE and Planet Wars. Please, @raiben @deantares @JJ @amorag check if the text I've added matches with the results we are using in this paper (the datasets are not in the repo). Also, a reference to the GPbot paper used must be added (IDK if it is the Evostar 14, Evostar 15, Cosecivi...).

**Comment by amorag** [comment] 2015-06-17 11:55
Yo no lo veo así, no es que no sepa la razón por la que lo hacéis.

Saludos.

De: Paloma de las Cuevas Delgado [mailto:notifications@github.com] 
Enviado el: miércoles, 17 de junio de 2015 13:01
Para: geneura-papers/2015-ECTA
CC: Antonio Mora
Asunto: Re: [2015-ECTA] Add problem description (#5)

Sigo sin saber por qué hablamos en inglés siendo todos españoles.

Easy. That significantly increases the possibility of others being interested in our work :) Or that maybe some others want to contribute.
If it's open it should be English written.
In addition, paper it's English written.
Aaaaand what's more addition is free practise for all.

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2015-ECTA/issues/5#issuecomment-112754260 .  https://github.com/notifications/beacon/AC6-WgIoLImhJiT7nJx2QYv18E2XyRHDks5oUUrdgaJpZM4FFHwd.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.6030 / Base de datos de virus: 4365/10036 - Fecha de publicación: 06/17/15

---

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5961 / Base de datos de virus: 4355/9987 - Fecha de publicación: 06/10/15
Base de datos de virus interno no está actualizado.

**Comment by JJ** [comment] 2015-06-17 16:37
@amorag please add description of Ms.Pacman, since @fliberatore does not seem to be availab.e

**Comment by fergunet** [comment] 2015-06-17 17:37
Forgot to add reference to this issue in commit 407c67646842a0677717ec392c64184d588162db

**Closed as completed** 2015-06-18 10:41 UTC
